### ISSUE TITLE
What do you mean with "relay"? 

### ISSUE THREAD

**Issue by jhave21** [jrmdev/mitm_relay#4]
First, great code :D 
But I wanna ask something, I'm really bad in Networking. What do you mean by relay ? Is that a proxy server or something? And what you mean by the argument "-l" is that something like a IP address of the server? Which you can intercept | listen all incoming request that was made for it?
Thanks

**Comment by jhave21** [comment]
thanks @jrmdev, really thanks, one last question please, does this work on remote PC's? from what I read in your code I guess yes, but I wanna hear it from you,

something came up my mind, 
>

**Comment by jhave21** [comment]
I accidentally closed the issue sorry about that, I commented again to reopen it :D

**Comment by jrmdev** [comment]
Hey,

I am unsure what you mean by remote PC's, it will work on any Linux system that has python installed.

As for ways to make you thick client connect to an IP of your choice instead of the default one, you could for example update your hosts file, create IPTables rules, do MiTM, configure a proxy within your client, etc.

Hope this helps.
